"""add generated videos table

Revision ID: 500ec2a5d7e5
Revises: 5a36a85158f3
Create Date: 2026-07-07 06:13:40.619076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500ec2a5d7e5'
down_revision: Union[str, Sequence[str], None] = '5a36a85158f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_videos_id'), 'generated_videos', ['id'], unique=False)
    op.create_index(op.f('ix_generated_videos_project_id'), 'generated_videos', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_videos_project_id'), table_name='generated_videos')
    op.drop_index(op.f('ix_generated_videos_id'), table_name='generated_videos')
    op.drop_table('generated_videos')
    # ### end Alembic commands ###
