"""add generated audio table

Revision ID: e2baa87abbf1
Revises: 3af03c953cac
Create Date: 2026-07-06 06:11:40.268524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2baa87abbf1'
down_revision: Union[str, Sequence[str], None] = '3af03c953cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_audio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_audio_id'), 'generated_audio', ['id'], unique=False)
    op.create_index(op.f('ix_generated_audio_project_id'), 'generated_audio', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_audio_project_id'), table_name='generated_audio')
    op.drop_index(op.f('ix_generated_audio_id'), table_name='generated_audio')
    op.drop_table('generated_audio')
    # ### end Alembic commands ###
